server:
  port: 8084
 
eureka:
 client:
  service-url:
    default-zone: http://localhost:8761
spring:
  application:
    name: TRAINER-SERVICE
    
  config:
      import: configserver:http://localhost:8888